// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWGIndustries.Data;

#nullable disable

namespace SWGIndustries.data.migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("SWGIndustries.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThemeMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SWGIndustries.Data.SWGAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SWGAccounts");
                });

            modelBuilder.Entity("SWGIndustries.Data.SWGCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SWGAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SWGAccountId");

                    b.ToTable("SWGCharacters");
                });

            modelBuilder.Entity("SWGIndustries.Data.SWGCharacter", b =>
                {
                    b.HasOne("SWGIndustries.Data.SWGAccount", "SWGAccount")
                        .WithMany("SWGCharacters")
                        .HasForeignKey("SWGAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SWGAccount");
                });

            modelBuilder.Entity("SWGIndustries.Data.SWGAccount", b =>
                {
                    b.Navigation("SWGCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
